{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubequery.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kubequery.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubequery.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubequery.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}