image:
  repository: ghcr.io/rorysavage77/kubequery-kubequery
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources: {}

rbac:
  create: true

serviceAccount:
  create: true
  name: ""

crds:
  install: true

nodeSelector: {}
tolerations: []
affinity: {}