image:
  repository: your-repo/ui-service
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources: {}

service:
  type: ClusterIP
  port: 80

nodeSelector: {}
tolerations: []
affinity: {}