image:
  repository: ghcr.io/rorysavage77/kubequery-ui-service
  tag: debug
  pullPolicy: IfNotPresent

replicaCount: 1

resources: {}

service:
  type: ClusterIP
  port: 80

nodeSelector: {}
tolerations: []
affinity: {}