image:
  repository: ghcr.io/rorysavage77/kubequery-ui-service
  tag: debug
  pullPolicy: IfNotPresent

replicaCount: 1

resources: {}

service:
  type: ClusterIP
  port: 80

nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: PGHOST
    value: kubequery-postgres
  - name: PGPORT
    value: "5432"
  - name: PGUSER
    value: kquser
  - name: PGPASSWORD
    value: changeme
  - name: PGDATABASE
    value: kqdb