# This rule is not used by the project kubequery itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over kubequery.rsavage.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubequery
    app.kubernetes.io/managed-by: kustomize
  name: postgresquery-admin-role
rules:
- apiGroups:
  - kubequery.rsavage.io
  resources:
  - postgresqueries
  verbs:
  - '*'
- apiGroups:
  - kubequery.rsavage.io
  resources:
  - postgresqueries/status
  verbs:
  - get
