---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubequery.cloudnexus.io
  resources:
  - postgresqueries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubequery.cloudnexus.io
  resources:
  - postgresqueries/finalizers
  verbs:
  - update
- apiGroups:
  - kubequery.cloudnexus.io
  resources:
  - postgresqueries/status
  verbs:
  - get
  - patch
  - update
