name: CI Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          - kubequery
          - ui-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch Docker image
        run: |
          if [ "${{ matrix.service }}" = "kubequery" ]; then
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag ghcr.io/${{ github.repository_owner }}/kubequery-kubequery:latest \
              --push .
          else
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag ghcr.io/${{ github.repository_owner }}/kubequery-ui-service:latest \
              --push ./ui-service
          fi