name: CI Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          - kubequery
          - ui-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service == 'kubequery' && '.' || './ui-service' }}
          file: ${{ matrix.service == 'kubequery' && 'Dockerfile' || './ui-service/Dockerfile' }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kubequery-${{ matrix.service }}:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            TARGETOS
            TARGETARCH